export const types = {
  GET_FILMS: '[FILMS] GET_FILMS',
  SEARCH_FILMS: '[FILMS] SEARCH_FILMS',
  PAGE_FILMS: '[FILMS] PAGE_FILMS',
  
  //ui
  INTRO_APP: '[UI] INTRO_APP',
  NOT_FOUND: '[UI] NOT_FOUND',
  START_APP: '[UI] START_APP',
  LOADING: '[UI] LOADING'
};